### ISSUE TITLE
GetGroupMemberlists 获取群成员列表抛出异常

### ISSUE THREAD

**Issue by ken3613** [laomms/XiaolzCSharp#1]
- 异常函数
```C#
public static int GetGroupMemberlists(long thisQQ, long groupQQ)
```
- 异常描述
严重错误：System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)

**Comment by laomms** [comment]
具体是哪个框架版本,我测试下好像没问题.

**Comment by ken3613** [comment]
已根据建议进行修改，但仍然出现错误
- SDK版本：2.8.4

**Comment by ken3613** [comment]
又或者说，该函数是否需要除了 
> 27, "取群成员列表" 
以外的权限，同时，如果权限不够是否会出现上述异常

**Comment by laomms** [comment]
如果几千个就设置为1024*1024

**Comment by ken3613** [comment]
在尝试设置为1024*100后异常消失，感谢！
